---
apiVersion: v1
kind: Secret
metadata:
  name: rbd-db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "rbd_system"
  POSTGRES_PASSWORD: "sUp3r_sEcUr3_rAnd0m_db_pAssw0rd_99!"
  POSTGRES_DB: "rbd_master"
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: return-by-death-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: rbd-db-credentials
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: rbd-web
    ports:
    - protocol: TCP
      port: 5432