---
apiVersion: v1
kind: Service
metadata:
  name: rbd-service
spec:
  selector:
    app: rbd-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: return-by-death
  labels:
    app: rbd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbd-web
  template:
    metadata:
      labels:
        app: rbd-web
    spec:
      containers:
      - name: app-container
        image: return-by-death-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: rbd-db-credentials
        env:
        - name: DB_HOST
          value: "db-svc"
        - name: HOME
          value: /tmp
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: cache-volume
          mountPath: /app/cache
        - name: tmp-volume 
          mountPath: /tmp
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}